import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowRight, Bell, BrainCircuit, Building2, ChartNoAxesCombined, Check, CheckCheck, ChevronDown, CircleHelp, Clock3, Fingerprint, Globe, LayoutDashboard, LockKeyhole, Network, Pause, Play, Radar, Radio, RadioTower, Send, Shield, ShieldAlert, ShieldCheck, Siren, Terminal, Users, X, Zap } from 'lucide-react';
import type { ReactNode } from 'react';
import CyberMap from './CyberMap';
import type { ThreatType } from './CyberMap';

type Incident = { id: string; level: string; time: string; title: string; description: string; status: string; target: string; type: string };
const incidents: Incident[] = [
  { id: 'INC-2026-0892', level: 'CRITICAL', time: '14:26:12', title: 'Intrusi SCADA Pembangkit Jawa-Bali', description: 'Upaya injeksi firmware berbahaya terdeteksi di sub-stasiun barat. Protokol isolasi segmentasi fisik diaktifkan otomatis.', status: 'AIR-GAP DIKUNCI', target: 'Energi · SCADA Jawa-Bali', type: 'Firmware injection' },
  { id: 'INC-2026-0891', level: 'HIGH', time: '14:19:40', title: 'Spear-Phishing Pejabat Hankam', description: '42 tautan credential harvesting ditargetkan via email dinas. Seluruh domain penyerang telah di-sinkhole.', status: '42/42 SINKHOLED', target: 'Pemerintahan · Email dinas', type: 'Spear-phishing' },
  { id: 'INC-2026-0890', level: 'MEDIUM', time: '14:02:18', title: 'Volumetrik DDoS Portal Publik', description: 'Flood SYN/UDP 450 Gbps menargetkan server kependudukan. Traffic dialihkan ke scrubbing center.', status: 'MITIGASI BERHASIL', target: 'Layanan publik · Registrasi', type: 'DDoS SYN/UDP' },
];
const units = [ { name: 'Satgas Defensif Alpha', sub: '32 Operator aktif · Kapasitas 91%', status: 'SIAP TEMPUR', icon: ShieldCheck, color: 'cyan' }, { name: 'Tim Forensik Digital', sub: '18 Spesialis · Analisis artefak APT', status: 'INVESTIGASI', icon: Fingerprint, color: 'blue' }, { name: 'Unit Kontra-Intelijen', sub: '14 Agen sinyal · Operasi senyap', status: 'PATROLI', icon: RadioTower, color: 'purple' } ];
const sectors = ['Energi', 'Keuangan', 'Telekomunikasi', 'Pemerintahan', 'Transportasi', 'Kesehatan', 'Pangan', 'Pertahanan', 'Sumber Daya Air', 'Layanan Publik', 'Pendidikan', 'Manufaktur'];
const navItems = [{name:'Pusat Komando', icon:LayoutDashboard},{name:'Pantauan Ancaman',icon:Radar},{name:'Infrastruktur Kritis',icon:Building2},{name:'Insiden & Respons',icon:ShieldAlert},{name:'Intelijen Siber',icon:Fingerprint}];
const heights = [25,32,22,38,43,28,38,50,39,57,49,35,65,58,43,53,74,60,48,68,83,96,87,76,57,66,49,42,55,37,45,59,42,32,47,65,52,46,61,81,100,78,64,59,48,42,57,39,46,35,27,38,29,22,34,25,20,27,19,16];
type ModalType = 'omega' | 'isolate' | 'cert' | 'coordinate' | 'detail' | 'profile' | 'help' | null;
type Log = { time: string; action: string; status: string };
function Badge({ children, color = 'cyan' }: { children: ReactNode; color?: string }) { return <span className={`badge ${color}`}>{children}</span>; }
function SectionHeading({ icon, title, right }: {icon: ReactNode; title:string; right?:ReactNode}) { return <div className="section-heading"><div className="heading-label">{icon}<h2>{title}</h2></div>{right}</div>; }

export default function App() {
  const [tab, setTab] = useState('Pusat Komando');
  const [filter,setFilter] = useState<ThreatType>('all');
  const [boosted,setBoosted] = useState(false);
  const [omega,setOmega] = useState(false);
  const [paused,setPaused] = useState(false);
  const [counter,setCounter] = useState(4829140);
  const [now,setNow] = useState(new Date());
  const [modal,setModal] = useState<ModalType>(null);
  const [detail,setDetail] = useState<Incident>(incidents[0]);
  const [notifications,setNotifications] = useState(false);
  const [read,setRead] = useState(false);
  const [toast,setToast] = useState('');
  const [selectedSectors,setSelectedSectors] = useState(['Energi']);
  const [isolated,setIsolated] = useState<string[]>([]);
  const [agencies,setAgencies] = useState(['BSSN','TNI Siber','Polri']);
  const [bulletin,setBulletin] = useState('Peringatan dini: peningkatan aktivitas intrusi SCADA dan kampanye spear-phishing. Segera audit akses, perbarui aturan firewall, dan verifikasi seluruh tautan email dinas.');
  const [logs,setLogs] = useState<Log[]>([{time:new Date().toISOString(),action:'Sesi komando simulasi dimulai',status:'AKTIF'}]);
  const dialogRef = useRef<HTMLDialogElement>(null);
  useEffect(() => { const timer = window.setInterval(() => setNow(new Date()),1000); return () => clearInterval(timer); },[]);
  useEffect(() => { if(paused) return; const timer = window.setInterval(() => setCounter(n => n + Math.floor(Math.random()*5)+1),3500); return () => clearInterval(timer); },[paused]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''),5000); return () => clearTimeout(timer); },[toast]);
  useEffect(() => { if (modal) dialogRef.current?.showModal(); else dialogRef.current?.close(); },[modal]);
  const time = now.toLocaleTimeString('en-GB',{timeZone:'Asia/Jakarta'});
  const logAction = (action:string) => { setLogs(l => [{time:new Date().toISOString(),action,status:'SIMULASI BERHASIL'},...l]); setToast(action); };
  const exportLogs = () => {
    const rows = [['timestamp','action','status'], ...logs.map(l=>[l.time,l.action,l.status]), ...incidents.map(i=>[i.time,i.title,i.status])];
    const csv = '\uFEFF' + rows.map(row => row.map(value => `"${value.replace(/"/g,'""')}"`).join(',')).join('\r\n');
    const url = URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));
    const a = document.createElement('a'); a.href=url; a.download=`forensik-simulasi-${now.toISOString().slice(0,10)}.csv`; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
    logAction('Log forensik simulasi berhasil diekspor ke CSV.');
  };
  const openDetail = (incident:Incident) => {setDetail(incident);setModal('detail');setNotifications(false);};
  const toggleChoice = (value:string, selected:string[], setter:(s:string[])=>void) => setter(selected.includes(value) ? selected.filter(s=>s!==value) : [...selected,value]);
  const confirmAction = () => {
    if (modal==='omega') { setOmega(!omega); logAction(omega ? 'Protokol Omega dinonaktifkan. Mode pertahanan normal dipulihkan.' : 'Simulasi Protokol Omega aktif. Gateway masuk ke mode lockdown.'); }
    if (modal==='isolate') { setIsolated([...new Set([...isolated,...selectedSectors])]);logAction(`Simulasi isolasi berhasil: ${selectedSectors.join(', ')}.`); }
    if (modal==='cert') logAction(`Buletin CERT simulasi dibuat untuk 1.420 institusi: ${bulletin}`);
    if (modal==='coordinate') logAction(`Kanal koordinasi simulasi dibuka: ${agencies.join(', ')}.`);
    setModal(null);
  };
  const titles: Record<Exclude<ModalType,null>,string> = {omega:omega?'Nonaktifkan Protokol Omega':'Aktifkan Protokol Omega',isolate:'Isolasi Sektor Terdampak',cert:'Rilis Peringatan CERT',coordinate:'Koordinasi Lintas Instansi',detail:'Detail & Log Forensik',profile:'Profil Operator',help:'Tentang Pusat Komando'};
  const incidentCards = incidents.map(incident => <article key={incident.id} className={`incident-card ${incident.level.toLowerCase()}`}><div className="incident-meta"><Badge color={incident.level==='CRITICAL'?'red':incident.level==='HIGH'?'blue':'neutral'}><i/>{incident.level}</Badge><time>{incident.time} WIB</time></div><h3>{incident.title}</h3><p>{incident.description}</p><div className="incident-foot"><span><CheckCheck size={12}/>{incident.status}</span><button onClick={()=>openDetail(incident)}>Detail <ArrowRight size={13}/></button></div></article>);

  return <div className={paused ? 'app paused' : 'app'}>
    <header className="top-header"><a href="#" className="brand" onClick={e=>{e.preventDefault();setTab('Pusat Komando');}}><div className="brand-mark"><Shield size={29}/><LockKeyhole className="brand-lock" size={12}/><i/></div><div><strong>BADAN PERTAHANAN SIBER NASIONAL</strong><span>REPUBLIK INDONESIA <b> / </b> CYBER DEFENSE COMMAND</span></div></a><div className="header-right"><div className="defcon"><Siren size={17}/><div><strong>{omega?'LOCKDOWN':'DEFCON 2'}</strong><span>{omega?'OMEGA ACTIVE':'HIGH ALERT'}</span></div></div><div className="header-clock"><div><i className="status-dot"/><span>WIB</span><strong>{time}</strong></div><span>UTC {now.toLocaleTimeString('en-GB',{timeZone:'UTC'})} <b> / </b> SYNC VALID</span></div><div className="notification-wrap"><button className={`icon-button notification-button ${notifications?'active':''}`} aria-label="Notifikasi" onClick={()=>setNotifications(!notifications)}><Bell size={19}/>{!read&&<i/>}</button>{notifications&&<div className="notification-menu"><div><strong>Notifikasi operasi</strong><button title="Tandai semua dibaca" onClick={()=>setRead(true)}><CheckCheck size={17}/></button></div><small>{read?'Semua notifikasi telah dibaca':'3 peringatan baru · Data simulasi'}</small>{incidents.map(i=><button key={i.id} onClick={()=>openDetail(i)}><span className={`status-dot ${i.level==='CRITICAL'?'red-dot':''}`}/><span>{i.title}<small>{i.time} WIB</small></span><ArrowRight size={14}/></button>)}</div>}</div><button className="profile" onClick={()=>setModal('profile')}><div><strong>Kpt. A. Sharma</strong><span>AKSES LEVEL 5 <i/></span></div><div className="avatar">AS</div><ChevronDown size={13}/></button></div></header>
    <div className="navigation-bar"><nav>{navItems.map(({name,icon:Icon})=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon size={16}/>{name}{name==='Insiden & Respons'&&<span className="nav-count">3</span>}</button>)}</nav><div className="nav-status"><i className="status-dot"/>SELURUH SISTEM OPERASIONAL<button aria-label="Informasi aplikasi" onClick={()=>setModal('help')}><CircleHelp size={16}/></button></div></div>
    <main>
      <section className={`command-banner ${omega?'omega-active':''}`}><div className="banner-grid"/><div className="banner-content"><div className="eyebrow"><span><i className="status-dot"/>DEFENSE CORE GRID</span><b>//</b> SEC-LEVEL 5 <span className="simulation-tag">MODE SIMULASI</span></div><h1>Pusat Kendali Operasi Siber Strategis</h1><div className="command-status"><span><ShieldCheck size={14}/>Jaringan nasional terlindungi</span><i/><span className="red-text"><i className="status-dot red-dot"/>{omega?'Protokol Omega: Lockdown Aktif':'Status: Siaga Tinggi (DEFCON 2)'}</span><i/><span className="muted">Konsensus node <b>48/48 aktif</b></span></div></div><div className="banner-actions"><button className={`shield-button ${boosted?'boosted':''}`} onClick={()=>{setBoosted(!boosted);logAction(!boosted?'Shield simulasi ditingkatkan ke 100%.':'Shield simulasi dikembalikan ke mode standar.');}}><ShieldCheck size={15}/><span>INTEGRITAS SHIELD</span><b>{boosted?'100%':'98.4%'}</b></button><button className={`primary-button omega-button ${omega?'danger-button':''}`} onClick={()=>setModal('omega')}><Zap size={17}/>{omega?'OMEGA AKTIF · LOCKDOWN':'PROTOKOL OMEGA'}<ArrowRight size={16}/></button></div></section>
      <div className="kpi-grid">
        <div className="kpi-card"><div className="kpi-heading"><span>SERANGAN DITANGKIS <b>(24 JAM)</b></span><ShieldCheck size={19}/></div><div className="kpi-value"><strong>{counter.toLocaleString('id-ID')}</strong><Badge color="red">↗ 14.2% Anomali</Badge></div><svg viewBox="0 0 320 28" preserveAspectRatio="none" className="sparkline"><defs><linearGradient id="spark-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#28cad5" stopOpacity=".25"/><stop offset="100%" stopColor="#28cad5" stopOpacity="0"/></linearGradient></defs><path d="M0 24L12 22L20 25L30 18L40 20L48 15L58 19L70 12L82 14L90 8L100 12L111 7L120 13L131 9L141 16L153 12L164 16L175 10L187 14L198 6L210 10L218 3L229 8L239 6L248 12L260 7L269 10L280 3L292 7L305 2L320 5 L320 28L0 28Z" fill="url(#spark-fill)"/><path d="M0 24L12 22L20 25L30 18L40 20L48 15L58 19L70 12L82 14L90 8L100 12L111 7L120 13L131 9L141 16L153 12L164 16L175 10L187 14L198 6L210 10L218 3L229 8L239 6L248 12L260 7L269 10L280 3L292 7L305 2L320 5" fill="none" stroke="#35ccdc" strokeWidth="1.5"/></svg><div className="kpi-footer"><span>T₀ − 24H</span><span>PUNCAK: <b>128.4K/menit</b></span></div></div>
        <div className="kpi-card"><div className="kpi-heading"><span>INFRASTRUKTUR KRITIS</span><Building2 size={19}/></div><div className="kpi-value"><strong>{isolated.length?'99.82':'99.98'}<small>%</small></strong><Badge>{isolated.length?'SEKTOR TERISOLASI':'STABIL NASIONAL'}</Badge></div><div className="kpi-track"><span style={{width:'99.98%'}}/></div><div className="kpi-footer"><span>Energi, Keuangan, Telco</span><span><b>12 sektor aktif</b></span></div></div>
        <div className="kpi-card"><div className="kpi-heading"><span>ANCAMAN APT AKTIF</span><Radar size={19} className="red-text"/></div><div className="kpi-value"><strong className="red-text">3 <small>Terdeteksi</small></strong><Badge color="red">PRIORITAS TINGGI</Badge></div><div className="kpi-track threat-track"><span/><span/></div><div className="kpi-footer"><span className="cyan-text">1 Dinetralisir</span><span className="red-text">2 Dalam karantina</span></div></div>
        <div className="kpi-card"><div className="kpi-heading"><span>KECEPATAN RESPONS AI</span><BrainCircuit size={19}/></div><div className="kpi-value"><strong>42 <small>Detik</small></strong><Badge color="blue">SUB-MENIT MTTR</Badge></div><div className="segmented-track">{[1,2,3,4,5,6,7,8,9,10,11,12].map(n=><i key={n} className={n<10?'filled':''}/>)}</div><div className="kpi-footer"><span>Otonom: <b>88%</b></span><span>Intervensi manusia: <b>12%</b></span></div></div>
      </div>
      {(tab==='Pusat Komando'||tab==='Pantauan Ancaman')&&<div className="main-grid"><div className="left-column"><CyberMap filter={filter} setFilter={setFilter} paused={paused}/><section className="panel spectrum-panel"><SectionHeading icon={<ChartNoAxesCombined size={18}/>} title="Spektrum Serangan & Throughput" right={<span className="predictive"><i className="status-dot"/>AI PREDICTIVE SHIELDING AKTIF</span>}/><div className="spectrum-body"><div className="chart-y"><span>500</span><span>250</span><span>0</span></div><div className="spectrum-chart"><div className="chart-grid"/>{heights.map((h,i)=><div key={i} className={`spectrum-bar ${h>85?'spike':''}`} style={{height:`${h}%`,opacity:h>85?1:0.4+h/150}} title={`${String(Math.floor(i/60*24)).padStart(2,'0')}:${String(Math.floor(i%2*30)).padStart(2,'0')} WIB · ${Math.round(h*4.82)} Gbps (simulasi)`}/>)}<div className="peak-label">482 Gbps <span>↑</span></div></div></div><div className="chart-x"><span>00:00</span><span>04:00</span><span>08:00</span><span>12:00</span><span>16:00</span><span>20:00</span><span>23:59 WIB</span></div><div className="spectrum-footer"><span><i className="status-dot red-dot"/>LONJAKAN TERBESAR: <b>482 Gbps</b> <span className="muted">(08:45 WIB)</span></span><span className="cyan-text"><ShieldCheck size={12}/>BERHASIL DITANGKIS</span></div></section></div><aside className="right-column"><section className="panel incidents-panel"><SectionHeading icon={<span className="status-dot red-dot pulse"/>} title="Peringatan Darurat Siber" right={<button className={`live-toggle ${paused?'is-paused':''}`} title={paused?'Lanjutkan stream simulasi':'Jeda stream simulasi'} onClick={()=>setPaused(!paused)}>{paused?<Play size={10}/>:<Pause size={10}/>} {paused?'DIJEDA':'LIVE'}</button>}/><div className="incident-list">{incidentCards}</div><button className="all-incidents" onClick={()=>setTab('Insiden & Respons')}>Lihat seluruh insiden <span>3 aktif <ArrowRight size={13}/></span></button></section><section className="panel readiness-panel"><SectionHeading icon={<Users size={18}/>} title="Kesiagaan Satuan Tugas" right={<span className="mono muted">3 UNIT</span>}/><div className="unit-list">{units.map(({name,sub,status,icon:Icon,color})=><button key={name} className="unit" onClick={()=>{setAgencies([name]);setModal('coordinate');}}><span className={`unit-icon ${color}`}><Icon size={19}/></span><span className="unit-info"><strong>{name}</strong><small>{sub}</small></span><Badge color={color}>{status}</Badge></button>)}</div><div className="unit-footer"><i className="status-dot"/><span>64 PERSONEL <b> / </b> SELURUH UNIT TERHUBUNG</span></div></section></aside></div>}
      {tab==='Infrastruktur Kritis'&&<section className="panel secondary-view"><SectionHeading icon={<Building2 size={20}/>} title="Status Infrastruktur Kritis Nasional" right={<Badge>12 SEKTOR TERPANTAU</Badge>}/><p className="view-description">Pemantauan kesiapan jaringan dan segmentasi sektor strategis. Seluruh status merupakan data simulasi.</p><div className="sector-grid">{sectors.map((sector,i)=><article className="sector-card" key={sector}><Building2 size={23}/><Badge color={isolated.includes(sector)?'red':'cyan'}>{isolated.includes(sector)?'TERISOLASI':'OPERASIONAL'}</Badge><h3>{sector}</h3><p>Gateway {String(i+1).padStart(2,'0')} · 4 node terhubung</p><div className="kpi-track"><span style={{width:isolated.includes(sector)?'30%':'99.9%'}}/></div><button onClick={()=>{if(isolated.includes(sector)){setIsolated(isolated.filter(s=>s!==sector));logAction(`Koneksi sektor ${sector} dipulihkan dalam simulasi.`);}else {setSelectedSectors([sector]);setModal('isolate');}}}>{isolated.includes(sector)?'Pulihkan koneksi':'Kelola isolasi'} <ArrowRight size={13}/></button></article>)}</div></section>}
      {tab==='Insiden & Respons'&&<section className="panel secondary-view"><SectionHeading icon={<ShieldAlert size={20}/>} title="Insiden & Respons Nasional" right={<button className="secondary-button" onClick={exportLogs}><ArrowDownToLine size={14}/>Ekspor laporan</button>}/><p className="view-description">3 insiden terdeteksi · 2 dalam penanganan · 1 berhasil dimitigasi. Klik Detail untuk meninjau jejak forensik.</p><div className="expanded-incidents">{incidentCards}</div><h3 className="activity-heading">Jejak Aktivitas Operator</h3><div className="activity-list">{logs.map((log,i)=><div key={i}><Clock3 size={15}/><time>{new Date(log.time).toLocaleTimeString('id-ID')}</time><span>{log.action}</span><Badge>{log.status}</Badge></div>)}</div></section>}
      {tab==='Intelijen Siber'&&<section className="panel secondary-view"><SectionHeading icon={<Fingerprint size={20}/>} title="Intelijen & Analisis Ancaman" right={<Badge color="purple">THREAT INTELLIGENCE</Badge>}/><p className="view-description">Ringkasan intelijen dari skenario latihan nasional. Bukan informasi ancaman dunia nyata.</p><div className="intel-grid">{[{name:'APT-28 / Simulasi',tech:'T1566 · Initial Access',text:'Kampanye spear-phishing menyasar email dinas. Indikator telah disalurkan ke sinkhole nasional.',i:1},{name:'SCADA / Firmware Injection',tech:'T0857 · System Firmware',text:'Modifikasi firmware pada jaringan industri. Air-gap aktif dan artefak sedang ditinjau tim forensik.',i:0},{name:'Botnet / Volumetric DDoS',tech:'T1498 · Network Denial of Service',text:'Lonjakan SYN/UDP terdistribusi. Scrubbing center berhasil memitigasi arus 450 Gbps.',i:2}].map(x=><article className="intel-card" key={x.name}><Radar size={25}/><Badge color="purple">ANALISIS SIMULASI</Badge><h3>{x.name}</h3><small>{x.tech}</small><p>{x.text}</p><button className="secondary-button" onClick={()=>openDetail(incidents[x.i])}>Buka analisis <ArrowRight size={14}/></button></article>)}</div></section>}
      <section className="panel tactical-bar"><div className="tactical-label"><span className="terminal-icon"><Terminal size={21}/></span><div><h2>Aksi Taktis & Penanggulangan Krisis</h2><p>OTORISASI LEVEL 5 <b>//</b> SELURUH AKSI DALAM MODE SIMULASI</p></div></div><div className="tactical-buttons"><button className="secondary-button red-text" onClick={()=>{setSelectedSectors(['Energi']);setModal('isolate');}}><ShieldAlert size={15}/>Isolasi Sektor</button><button className="secondary-button" onClick={()=>setModal('cert')}><Radio size={15}/>Peringatan CERT</button><button className="secondary-button light-button" onClick={exportLogs}><ArrowDownToLine size={15}/>Ekspor Log</button><button className="primary-button" onClick={()=>{setAgencies(['BSSN','TNI Siber','Polri']);setModal('coordinate');}}><Network size={15}/>Koordinasi Instansi<ArrowRight size={14}/></button></div></section>
    </main>
    <footer><div><span><LockKeyhole size={12}/><b>AES-256-GCM</b><i/>JAKARTA GATEWAY <span className="cyan-text">● OPERASIONAL</span></span><p>DASHBOARD DEMONSTRASI · DATA DAN AKSI PERTAHANAN MERUPAKAN SIMULASI</p></div><div className="footer-right"><span><span className="red-text">HOTLINE DARURAT SIBER 24/7</span><strong>121-SIBER-OPS</strong></span><p>© 2026 BADAN PERTAHANAN SIBER NASIONAL <b> / </b> CONCEPT INTERFACE</p></div></footer>
    <dialog ref={dialogRef} className="command-dialog" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}>{modal&&<><div className="dialog-top"><span><Shield size={17}/>SECURE COMMAND <b>//</b> LEVEL 5</span><button aria-label="Tutup dialog" onClick={()=>setModal(null)}><X size={20}/></button></div><div className="dialog-body"><Badge color={modal==='omega'?'red':'cyan'}>LINGKUNGAN SIMULASI</Badge><h2>{titles[modal]}</h2>
      {modal==='omega'&&<><p>{omega?'Akhiri lockdown simulasi dan kembalikan gateway ke mode pertahanan standar.':'Protokol Omega akan mensimulasikan karantina subnet nasional. Seluruh gateway dialihkan ke mode lockdown dan lalu lintas masuk dibatasi.'}</p><div className="warning-box"><ShieldAlert size={22}/><span>Konfirmasi otorisasi Anda sebelum melanjutkan. Aksi ini hanya mengubah status dashboard, bukan jaringan nyata.</span></div><div className="detail-row"><span>Operator</span><strong>Kpt. A. Sharma · Level 5</strong></div><div className="detail-row"><span>Cakupan</span><strong>48 node / 12 sektor nasional</strong></div></>}
      {modal==='isolate'&&<><p>Pilih sektor untuk menjalankan simulasi segmentasi air-gap. Koneksi dapat dipulihkan melalui tab Infrastruktur Kritis.</p><div className="choice-grid">{sectors.slice(0,6).map(s=><label key={s}><input type="checkbox" checked={selectedSectors.includes(s)} onChange={()=>toggleChoice(s,selectedSectors,setSelectedSectors)}/>{s}</label>)}{selectedSectors.filter(s=>!sectors.slice(0,6).includes(s)).map(s=><label key={s}><input type="checkbox" checked onChange={()=>toggleChoice(s,selectedSectors,setSelectedSectors)}/>{s}</label>)}</div><div className="warning-box"><ShieldAlert size={20}/>{selectedSectors.length} sektor akan diisolasi dalam simulasi.</div></>}
      {modal==='cert'&&<><p>Susun buletin untuk daftar distribusi CERT nasional. Buletin akan disimpan ke log lokal; tidak dikirim ke institusi nyata.</p><label className="field-label" htmlFor="bulletin">ISI BULETIN CERT</label><textarea id="bulletin" value={bulletin} onChange={e=>setBulletin(e.target.value)} rows={5}/><div className="detail-row"><span>Distribusi simulasi</span><strong>1.420 institusi / CSIRT-ID</strong></div></>}
      {modal==='coordinate'&&<><p>Pilih unit untuk membuka kanal koordinasi latihan. Tidak ada koneksi ke sistem komunikasi instansi nyata.</p><div className="choice-grid">{[...new Set(['BSSN','TNI Siber','Polri',...agencies])].map(a=><label key={a}><input type="checkbox" checked={agencies.includes(a)} onChange={()=>toggleChoice(a,agencies,setAgencies)}/>{a}</label>)}</div><div className="warning-box cyan-box"><LockKeyhole size={19}/><span>Kanal latihan VIP · {agencies.length} unit dipilih</span></div></>}
      {modal==='detail'&&<><div className="detail-incident-title"><h3>{detail.title}</h3><Badge color={detail.level==='CRITICAL'?'red':'blue'}>{detail.level}</Badge></div><p>{detail.description}</p><div className="detail-row"><span>ID insiden</span><strong>{detail.id}</strong></div><div className="detail-row"><span>Target</span><strong>{detail.target}</strong></div><div className="detail-row"><span>Vektor</span><strong>{detail.type}</strong></div><div className="detail-row"><span>Status</span><strong className="cyan-text">{detail.status}</strong></div><div className="forensic-log"><span>{detail.time} [DETECT] Anomali teridentifikasi</span><span>{detail.time} [ANALYZE] Klasifikasi: {detail.type}</span><span>{detail.time} [RESPOND] {detail.status}</span><span>{detail.time} [AUDIT] Artefak simulasi tercatat</span></div></>}
      {modal==='profile'&&<><div className="profile-detail"><div className="avatar">AS</div><div><h3>Kpt. A. Sharma</h3><p>Satgas Reaksi Cepat · Operator Komando</p></div></div><div className="detail-row"><span>Hak akses</span><Badge>LEVEL 5 / ADMINISTRATOR</Badge></div><div className="detail-row"><span>Sesi</span><strong>Lingkungan simulasi lokal</strong></div><div className="detail-row"><span>Zona waktu</span><strong>Asia/Jakarta · UTC+7</strong></div></>}
      {modal==='help'&&<><p>Dashboard interaktif bertema pertahanan siber Indonesia. Citra satelit disediakan oleh Esri World Imagery; data ancaman, telemetri, dan seluruh aksi adalah simulasi lokal.</p><div className="help-items"><span><Globe size={18}/>Geser peta dan gunakan +/− untuk memperbesar.</span><span><Radar size={18}/>Filter DDoS, Ransomware, dan Zero-Day pada peta.</span><span><ShieldCheck size={18}/>Klik node untuk melihat status gateway.</span><span><ArrowDownToLine size={18}/>Ekspor insiden dan aksi operator sebagai CSV.</span></div><p className="muted">Tile resolusi tinggi memerlukan internet. Citra cadangan lokal ditampilkan bila sumber daring tidak tersedia. Citra satelit bukan siaran langsung.</p></>}
      </div><div className="dialog-actions"><button className="secondary-button" onClick={()=>setModal(null)}>{['detail','profile','help'].includes(modal)?'Tutup':'Batal'}</button>{!['detail','profile','help'].includes(modal)&&<button className={`primary-button ${modal==='omega'?'danger-button':''}`} disabled={(modal==='isolate'&&!selectedSectors.length)||(modal==='cert'&&!bulletin.trim())||(modal==='coordinate'&&!agencies.length)} onClick={confirmAction}>{modal==='cert'?<Send size={15}/>:<ShieldCheck size={15}/>} {modal==='omega'?(omega?'Nonaktifkan Omega':'Konfirmasi Aktivasi'):modal==='cert'?'Simpan & Rilis Simulasi':modal==='coordinate'?'Buka Kanal Simulasi':'Konfirmasi Isolasi'}</button>}{modal==='detail'&&<button className="primary-button" onClick={exportLogs}><ArrowDownToLine size={15}/>Unduh Log CSV</button>}</div></>}</dialog>
    {toast&&<div className="toast" role="status"><span><Check size={18}/></span><div><strong>PERINTAH DIPROSES</strong><p>{toast}</p></div><button aria-label="Tutup pemberitahuan" onClick={()=>setToast('')}><X size={17}/></button></div>}
  </div>;
}
